package com.example.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters
import com.example.data.model.CallLogEntry
import com.example.data.model.ChatConversation
import com.example.data.model.ChatMessageEntity
import com.example.data.model.SipAccount

/**
 * Accounts, call history and chat. Each platform opens it with its own builder
 * (Android keeps its file and migrations; Windows uses the bundled SQLite driver).
 */
@Database(
    entities = [SipAccount::class, CallLogEntry::class, ChatConversation::class, ChatMessageEntity::class],
    version = 2,
    exportSchema = false
)
@TypeConverters(Converters::class)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun sipAccountDao(): SipAccountDao
    abstract fun callLogDao(): CallLogDao
    abstract fun chatDao(): ChatDao

    companion object {
        const val FILE_NAME = "softphone.db"
    }
}

// Generated by Room for each platform
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
